### PR TITLE
Automatically release backfila

### PR DESCRIPTION
**Pull request by tso**

### CODE REVIEW

**Comment by tso** [comment]
This requires updates to the branch settings in the repo to update the required checks — We'll need to force merge this, wait for the build to happen on master and then update the required checks

**Comment by shellderp** [comment]
what is the outcome of this? it's not clear what the difference is between the old release task and the one you added

**Comment by tso** [comment]
> what is the outcome of this? it's not clear what the difference is between the old release task and the one you added

Outcome is each commit will just auto publish to maven central if tests pass on master

**Review by staktrace — APPROVED** [review]
Didn't look at this too closely but stamping to unblock.

**Review by mpawliszyn — APPROVED** [review]
The tests are failing though

**Pull request merged**
