### PR TITLE
Bump jetty version to 10

### PR DESCRIPTION
**Pull request by zpingcai**

### CODE REVIEW

**Review by shellderp — APPROVED** [review]

**Comment by zpingcai** [comment]
```
> Could not resolve all files for configuration ':client-jooq:classpath'.
   > Could not resolve org.jooq:jooq-codegen:3.13.5.
     Required by:
         project :client-jooq > nu.studer.jooq:nu.studer.jooq.gradle.plugin:5.2 > nu.studer:gradle-jooq-plugin:5.2
      > Could not resolve org.jooq:jooq-codegen:3.13.5.
         > Could not parse POM https://plugins.gradle.org/m2/org/jooq/jooq-codegen/3.13.5/jooq-codegen-3.13.5.pom
            > Could not resolve org.jooq:jooq-parent:3.13.5.
               > Could not resolve org.jooq:jooq-parent:3.13.5.
                  > Could not get resource 'https://plugins.gradle.org/m2/org/jooq/jooq-parent/3.13.5/jooq-parent-3.13.5.pom'.
                     > Could not GET 'https://jcenter.bintray.com/org/jooq/jooq-parent/3.13.5/jooq-parent-3.13.5.pom'.
                        > peer not authenticated
```
Thought they've resolved the expired certificate issue?

**Comment by shellderp** [comment]
jcenter is dead, right? We removed it from this repo. Maybe a jooq version upgrade is needed

**Comment by shellderp** [comment]
I can download that pom manually though..

**Comment by zpingcai** [comment]
> 

I think the main issue is `jcenter.bintray.com`'s certificate expired [last Friday](https://github.com/gradle/gradle/issues/22864#issuecomment-1327970886), but the issued has been resolved. I guess circle ci is using a cached certificate in its truststore?

**Comment by shellderp** [comment]
second build attempt  passed

**Pull request merged**
